## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    #obj = bld.create_ns3_program('lr-wpan-data-energy-model', ['reliability'])
    #obj.source = 'lr-wpan-data-energy-model.cc'

    #obj = bld.create_ns3_program('lr-wpan-energy-test', ['reliability'])
    #obj.source = 'lr-wpan-energy-test.cc'
